# Generated by Django 5.0.3 on 2024-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_concertrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_held',
            field=models.BooleanField(default=False, verbose_name='Прошел ли концерт'),
        ),
    ]
