# Generated by Django 5.0.3 on 2024-05-03 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 9, 9, 13, 783344), verbose_name='date of birth'),
        ),
    ]
