# Generated by Django 5.0.3 on 2024-05-07 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6MUWcJG6bgOMZIx6jCgCbPn2ctugc3wgcn8cYbA5JPfj1sOEf', upload_to='avatar/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2024, 5, 7, 20, 16, 29, 128425), verbose_name='date of birth'),
        ),
    ]
