# Generated by Django 5.0.3 on 2024-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_held',
            field=models.BooleanField(default=False),
        ),
    ]
